using Teamcenter.Soa.Client.Model;

namespace Teamcenter.Soa.Internal.Client.Model;

public class RulePatternImpl : RulePattern
{
	private readonly string mPattern;

	private readonly bool mAutoGen;

	private readonly int mInitVal;

	private readonly int mMaxVal;

	public string Pattern => mPattern;

	public bool Autogenerated => mAutoGen;

	public int InitialValue => mInitVal;

	public int MaximumValue => mMaxVal;

	public RulePatternImpl(string pattern, bool autoGen, int initVal, int maxVal)
	{
		mPattern = pattern;
		mAutoGen = autoGen;
		mInitVal = initVal;
		mMaxVal = maxVal;
	}
}
